/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-08-26 08:11:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Model.*;
import java.sql.*;
import java.util.*;
import java.text.*;

public final class sub1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(10);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("java.text");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("Model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>고교성적관리</title>\r\n");
      out.write("<style>\r\n");
      out.write("header {\r\n");
      out.write("	background: #59c;\r\n");
      out.write("	padding: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h1 {\r\n");
      out.write("	color: #fff;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 6px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("nav {\r\n");
      out.write("	background: #D8D;\r\n");
      out.write("	padding: 1px\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("	color: #25C;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("	padding: 2px 4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section {\r\n");
      out.write("	padding: 1px;\r\n");
      out.write("	background: #CCC;\r\n");
      out.write("	height:400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h2 {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer {\r\n");
      out.write("	background: #59c;\r\n");
      out.write("	padding: 1px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("footer p {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tr, th, td {\r\n");
      out.write("	border-style: solid;\r\n");
      out.write("	border-width: 1px;\r\n");
      out.write("	border-color: #888;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	width:450px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function check() {\r\n");
      out.write("		if (my.syear.value == \"\") {\r\n");
      out.write("			alert(\"학년정보가 입력되지 않았습니다!\");\r\n");
      out.write("			my.syear.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if (my.sclass.value == \"\") {\r\n");
      out.write("			alert(\"반정보가 입력되지 않았습니다!\");\r\n");
      out.write("			my.sclass.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if (my.sno.value == \"\") {\r\n");
      out.write("			alert(\"번호정보가 입력되지 않았습니다!\");\r\n");
      out.write("			my.sno.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if (my.sname.value == \"\") {\r\n");
      out.write("			alert(\"이름이 입력되지 않았습니다!\");\r\n");
      out.write("			my.sname.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if (my.birth.value == \"\") {\r\n");
      out.write("			alert(\"생년월일이 입력되지 않았습니다!\");\r\n");
      out.write("			my.birth.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if (my.gender.checked==\"\" && my.gender.checked==\"\") {\r\n");
      out.write("			alert(\"성별을 선택하세요!\");\r\n");
      out.write("			my.gender[0].focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		/*\r\n");
      out.write("		var genders = document.getElementsByName(\"gender\");\r\n");
      out.write("		if(!genders[0].checked && !genders[1].checked) {\r\n");
      out.write("			alert(\"성별선택\");\r\n");
      out.write("			genders[0].focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		*/\r\n");
      out.write("		if (my.tel1.value == \"\") {\r\n");
      out.write("			alert(\"전화번호가 입력되지 않았습니다!\");\r\n");
      out.write("			my.tel1.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if (my.tel2.value == \"\") {\r\n");
      out.write("			alert(\"전화번호가 입력되지 않았습니다!\");\r\n");
      out.write("			my.tel2.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		if (my.tel3.value == \"\") {\r\n");
      out.write("			alert(\"전화번호가 입력되지 않았습니다!\");\r\n");
      out.write("			my.tel3.focus();\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		alert(\"학생등록이 정상적으로 등록되었습니다\");\r\n");
      out.write("		return true;\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<h1>(과정평가형 정보처리산업기사)고교성적관리프로그램 ver2019-06</h1>\r\n");
      out.write("	</header>\r\n");
      out.write("	<nav>\r\n");
      out.write("		<a href=\"sub1.jsp\">학생등록</a>\r\n");
      out.write("		<a href=\"sub2.jsp\">성적입력</a> \r\n");
      out.write("		<a href=\"sub3.jsp\">성적조회</a> \r\n");
      out.write("		<a href=\"sub4.jsp\">반별통계</a> \r\n");
      out.write("		<a href=\"index.jsp\">홈으로</a>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<section>\r\n");
      out.write("		<h2>학생등록</h2>\r\n");
      out.write("		<form name=\"my\" method=\"post\" action=\"sub1pro.jsp\" onsubmit=\"return check()\">\r\n");
      out.write("			<table>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>학년</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"syear\">(예)1</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>반</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"sclass\">(예)01</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>번호</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"sno\">(예)01</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>이름</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"sname\" style=\"width: 230px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>생년월일</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"birth\" style=\"width: 230px\">(예)20190301</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>성별</th>\r\n");
      out.write("					<td><input type=\"radio\" name=\"gender\" value=\"M\">남성\r\n");
      out.write("						<input type=\"radio\" name=\"gender\" value=\"F\">여성</td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<th>전화번호</th>\r\n");
      out.write("					<td><input type=\"text\" name=\"tel1\" style=\"width: 70px\">-\r\n");
      out.write("						<input type=\"text\" name=\"tel2\" style=\"width: 70px\">-\r\n");
      out.write("						<input type=\"text\" name=\"tel3\" style=\"width: 70px\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("				<tr>\r\n");
      out.write("					<td colspan=\"2\" style=\"text-align: center;\">\r\n");
      out.write("					<input type=\"submit\" value=\"학생등록\">\r\n");
      out.write("					<input type=\"reset\" value=\"다시쓰기\" onclick=\"alert('정보를 지우고 처음부터 다시 입력합니다!')\"></td>\r\n");
      out.write("				</tr>\r\n");
      out.write("			</table>\r\n");
      out.write("		</form>\r\n");
      out.write("	</section>\r\n");
      out.write("	<footer>\r\n");
      out.write("		<p>HRDKOREA Copyright&copy;2016 All rights reserve. Human\r\n");
      out.write("			Resources Development Service of Korea</p>\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
